name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '4.0.2'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Download mandoc
        run: |
          wget https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz
          tar xf mandoc-1.14.6.tar.gz
          (cd mandoc-1.14.6/ && ./configure)
      - name: Run the default task
        run: bundle exec rake
